### ISSUE TITLE
6.0.0 Features/Roadmap [COMING THIS WEEK!!!]  - MAJOR RELEASE

### ISSUE THREAD

**Issue by Ks89** [Ks89/angular-modal-gallery#140]
As you probably know I'm working on angular-modal-gallery 6.0.0. It's already in alpha.

**Don't be scared, this will be a smaller major release than 5.0.0**. I want to update some APIs and update the build system to release the library on npm.

### `npm i --save @ks89/angular-modal-gallery`

**Also, change all imports from `'angular-modal-gallery'` to `'@ks89/angular-modal-gallery'`**

Right now, to test alphas, use `npm i --save @ks89/angular-modal-gallery@next`

Changes:
- [x] Support Angular Package Format specification v5 (**BREAKING CHANGE**)
- [x] Remove Angular 4 support (**BREAKING CHANGE**)
- [x] new package name `@ks89/angular-modal-gallery` (**to install use `npm i --save @ks89/angular-modal-gallery@next`**) (**BREAKING CHANGE**)
- [x] migrate to nwrl/nx 1.x.x
- [x] migrate to ng-packagr >=2
- [x] Description bottom margin in modal image is now 0px instead of 5px (**BREAKING CHANGE**)
- [x] move loadingConfig, description and downloadble into CurrentImageConfig (**BREAKING CHANGE**)
- [x] add full screen upper button as FULL Strategy (**BREAKING CHANGE**)
- [x] remove webpack example
- [x] (doc) update documentation website to 6.0.0 with new apis
- [x] (doc) fix scrolling issue in documentation website 
- [x] update all examples to angular 6, angular-cli 6, material 6 and universal 6
- [x] add an angular-cli example with angular 5 and angular-cli 1.7.x
- [x] and many more (I'll update this list ASAP)

This issue will be updated every time I'll implement something on a dedicated branch 'nwrlnx-090-ngpackagr2'

I will be really happy if you want to create pull requests or you want to talk with me about features, before the official release. So I'll be able to change my roadmap accordingly.

**Comment by Ks89** [comment]
Are you ready for summer?

![angular-modal-gallery image](https://github.com/Ks89/angular-modal-gallery/blob/nwrlnx-090-ngpackagr2/amg6.png?raw=true)

Version 6.0.0 will be red/orange :)

**Comment by Ks89** [comment]
PS: the first beta version is quite ready and also the documentation website (I'll create another repo with a different url - more info soon)

**Comment by Ks89** [comment]
Beta 1 released `npm i --save @ks89/angular-modal-gallery@latest`

Doc website released [HERE](https://ks89.github.io/angular-modal-gallery-2018-v6.github.io/)

**Comment by Enngage** [comment]
Hi, I've moved to 6.x. May I offer some features? 

- Gallery service should have a method for closing the modal gallery programatically. We are deleting images on the go and they 'stuck' displayed if they were focused before. 
- The preview/next thumbnails displayed when modal gallery is active are 'moving' depending on the aspect ratio of images. This means that if someone would try moving to next image, he needs to use mouse to navigate to thumbnail or he might accidentaly close modal because he clicked 'outside'. 

Thanks!

**Comment by Ks89** [comment]
> Gallery service should have a method for closing the modal gallery programatically

good idea

> The preview/next thumbnails displayed when modal gallery is active are 'moving' depending on the aspect ratio of images.

Mmm, yes because I'm using space-between as justify-content property of flex-box. I should try a different technique, but this will require more time to test and I have to reschedule 6.0.0 release in June.

> Also, there seems to an issue with the downloadable feature. Everything worked fine in v5, but as soon as I upgraded to 6, it navigates to the image in browser rather then downloading it

I don't know how to reproduce it. Also, I didn't change anything from 5 to 6.0.0 about this feature. Which OS and browsers are you using (please write also full browsers versions)? Did you try with other browsers?

**Comment by Enngage** [comment]
Yeah, I tried several browsers as well as forcingly clearing cache. I tested this right before upgrading and worked fine, the only thing I changed was that I:

- installed `@ks89/angular-modal-gallery` and removed the old package
- changed imports to `@ks89/angular-modal-gallery` 
- changed config to use ` [currentImageConfig]="{downloadable: true}`

I also tried using the exact same example you have in docs with:

```
<ks-modal-gallery [id]="0" [modalImages]="images"
    [currentImageConfig]="{downloadable: true}"
    [buttonsConfig]="buttonsConfigSimple"></ks-modal-gallery>


    public buttonsConfigSimple: ButtonsConfig = {
        visible: true,
        strategy: ButtonsStrategy.SIMPLE
      };
```

Not really sure whats going on, probably something in greater scheme of things..

**Comment by Enngage** [comment]
I wonder how the update for the[ SO answer](https://stackoverflow.com/questions/17527713/force-browser-to-download-image-files-on-click/17527821) here is relevant:

> UPDATE: As of spring 2018 this is no longer possible for cross-origin hrefs. So if you want to create <a href="https://i.imgur.com/IskAzqA.jpg" download> on a domain other than imgur.com it will not work as intended. Chrome deprecations and removals announcement

I do have images stored on different server so that would explain why it doesn't work. Still, it doesn't really explain why it worked just minutes before I upgraded :-)

**Comment by Ks89** [comment]
Interesting

So are you using images outside your server (not in assets folder of your angular app)? Are you using http or https?

**Comment by Ks89** [comment]
I pushed some commits with close method inside modal gallery service. I'll release it this weekend.

Now I'll start to try to reproduce the download issue.

**Comment by Ks89** [comment]
@Enngage I confirm the problem about image download.
I link this issue here #138 because It's better to merge all ideas into a single discussion.

The question is: "Is there an alternative to download static files automatically on client side [without to call a server with a specific logic] without this limitation when using files from other websites?"

**Comment by Enngage** [comment]
Thanks, I'll try the new version :-) I'm not so sure, but I will probably remove the download button alltogether and only open new tab with the image

**Comment by Ks89** [comment]
Beta2 released with close method + experimental impl to fix alignment of side previews

Please leave your feedback @Enngage

**Comment by Enngage** [comment]
Hey, just tried it and looks way better, thanks!

**Comment by Ks89** [comment]
did you try also on IE, Edge and if you can also on iOS? I'm a little bit scared about compatibility.

**Comment by Enngage** [comment]
It works fine in Edge. I don't really care for IE / Edge and possibly
safari as if people are using these browsers, its their fault. Angular in
general doesn't really work well in IE and Edge by itself.

**Comment by Ks89** [comment]
:) yes but I have to support those XD

Ok, I'll check on iOS and if everything is ok, I'll release the final next week.

**Comment by Ks89** [comment]
Doc updated with the doc for closeGallery method and some small fixes

https://ks89.github.io/angular-modal-gallery-2018-v6.github.io/

**Comment by Ks89** [comment]
6.0.0 final released

stackblitz 
https://angular-modal-gallery-v6.stackblitz.io

docs: https://ks89.github.io/angular-modal-gallery-2018-v6.github.io/

**Comment by Ks89** [comment]
ps: please let me know if everything is ok, so I'll deprecate all previous versions on npmjs
