### ISSUE TITLE
7.0.0 Features/Roadmap - HUGE MAJOR RELEASE [STABLE RELEASE IS COMING!!!]

### ISSUE THREAD

**Issue by Ks89** [Ks89/angular-modal-gallery#144]
From this summer I'm working on angular-modal-gallery 7.0.0

Expected changes **7.0.0**

- [x] add carousel features **(big feature)**
- [x] add carousel's previews features **(big feature)**
- [x] **gallery ids must be unique across the whole application**, so if you are using the library in multiple components of the same application, you must use different numeric ids (I suggest 0,1,2,3, 100,101, 200, 201 and so on) **BREAKING CHANGE**
- [x] new main example with 3 pages and navigation to split carousel, modal and plain gallery
- [x] require rxjs >= 6 (remove rxjs-compat) **BREAKING CHANGE**
- [x] change preview's sliding behaviour (simple and cleaner then before, taken from carousel's previews) **BREAKING CHANGE**
- [x] re-write tests for previews component in modal view with the new logic
- [x] it will require Angular >=7 (probably also Angular 6, but this time I won't promise anything) **BREAKING CHANGE**
- [x] switch to the official ng lib features in angular-cli >= 6 with the new Angular specification **BREAKING CHANGE**
- [x] add new method into galleryservice called 'navigateGallery'
- [x] new doc website https://github.com/Ks89/angular-modal-gallery-2018-v7.github.io
- [x] update all local examples
- [x] add carousel, plain and modal images to readme.md
- [x] update stackblitz example
- [x] test id-validator.service
- [x] add configurable breakpoints to carousel's previews
- [x] test carousel component 
- [x] test carousel-previews component
- [x] update doc website with this info (#141) [requested by @dbayonacode]:
   ```
   please don't use "this.images.push(img);".  When you want to modify images, you have to re-assign 
   the array to the images input because I'm using OnPush strategy to improve performance.
   So, don't do this.images.push, but instead:
   const newImageArray= ....;
   this.images = newImageArray;
   otherwise change detection won't be triggered.
   ```

<br>

Expected changes **7.1.0 -> 7.X.X**

- add carousel features also to modal view (requested by @hn6pot in #152)
- fix: Add output to ModalGalleryComponent emitting whenever the image is changed (requeste by @ srtab in #165)
- investigate about image download with a better approach

Next:

- add image rotation feature with a new upper button (probably also with some shortcuts) #143 [MORE DIFFICULT THAN EXPECTED BECAUSE OF https://stackoverflow.com/questions/16301625/rotated-elements-in-css-that-affect-their-parents-height-correctly] 

<br>
Feel free to propose new features.

Public branch available here [7.0.0](https://github.com/Ks89/angular-modal-gallery/tree/700)
I want to release this major version during the autumn with angular 7 support.

**Comment by Ks89** [comment]
link #143

**Comment by Ks89** [comment]
I started to work on a new big feature: carousel

**Comment by Ks89** [comment]
New documentation website (still not updated to 7.x.x) with better accessibility, performance and SSR support with angular-universal: https://github.com/Ks89/angular-modal-gallery-2018-v7.github.io

I'll update and publish it after the first alphas of the library :)

**Comment by Ks89** [comment]
@ks89/angular-modal-gallery version 7.0.0 will require rxjs 6 (no more rxjs-compat). So the minimum version of Angular will 6.0.0 as already anticipated.

**Comment by Ks89** [comment]
**If angular-cli 7 will force all library developers to switch to Angular 7, also @ks89/angular-modal-gallery will require angular 7.**

**Comment by Ks89** [comment]
Warning - breaking change:
I changed how previews scroll in modal view. The rule is:

if number of previews % 2 === 0 =>
- a click on the first half => previews
- a click on the second half => next
else =>
- a click on the first half => previews
- a click in the middle => ignore the click without doing anything
- a click on the second half => next

Why?
Because, it's simpler and cleaner and also it's more predictable, avoiding bugs and stupid issues.

**Comment by Ks89** [comment]
I decided to write a new scroll feature also with animation for carousel's previews. It's still experimental, but when I'll I have a working impl I'll release a public beta of 7.0.0 (probably at the end of September or before)

In future releases I'll port this also for modal previews. Right now I prefer to wait, to do small steps, without break everything :)

**Comment by Ks89** [comment]
Ok, after many experiments I decided to revert the scrolling carousel's previews, because It's absolutely impossibile to implement it in a stable way for all browsers, all resolutions and also for many input parameters.
I prefer to create a simplified and stable implementation that I can improve in future releases, then delay the current version.

**Comment by Ks89** [comment]
feature "carousel's previews" completed.
Now I'm fixing some tests.
This weekend I'll publish the first public alpha.

**Comment by Ks89** [comment]
Alpha 1 released.
Don's use it in production, but please try it and let me know every issue to fix it before the final release.

To install `npm i --save @ks89/angular-modal-gallery@next`

# 7.0.0-alpha.1
### Features
- add (plain) carousel with previews
- new method in GalleryService called 'navigateGallery'
- gallery ids must be unique across the whole application **(BREAKING CHANGE)**
- requires rxjs >= 6 **(BREAKING CHANGE)**
- requires angular >= 6 **(BREAKING CHANGE)**
- change preview's sliding behaviour (simple and cleaner then before, taken from carousel's previews) **(BREAKING CHANGE)**

### Internal library changes
- migrate to the official ng lib features in angular-cli >= 6.2

### Demos
- update main example with multiple pages
- upgrade all examples with multiple pages

### Documentations
- new documentation website https://github.com/Ks89/angular-modal-gallery-2018-v7.github.io (still not published)

**Comment by Ks89** [comment]
I found an issue with fixed width carousel on mobile. I pushed a fix and I'll release it in alpha2 in a couple of days.

**Comment by Ks89** [comment]
Alpha 2 released https://github.com/Ks89/angular-modal-gallery/releases/tag/v.7.0.0-alpha.2

**Comment by Ks89** [comment]
Stackblitz example updated to alpha 2: https://angular-modal-gallery-v7.stackblitz.io/

**Comment by Ks89** [comment]
With the next release (BETA 1) I'll publish the documentation website (probably at 15th of October). Now I'm writing unit testing for the new carousel components.

**Comment by Ks89** [comment]
I had to release 6.3.0 before 7.0.0-beta.1, so there will be a small delay

**Comment by Ks89** [comment]
Ok 6.3.0 has been released, I can back again to 7.0.0 beta

**Comment by Ks89** [comment]
BETA 1 released!!!!
There are some bugs about carousels with firefox, IE and Edge, however I'll fix they in upcoming betas.

Documentation website is coming really soon, I'm ready to release the first public version.

**Comment by Ks89** [comment]
Doc website 7.0.0-beta.1 released here: [https://ks89.github.io/angular-modal-gallery-2018-v7.github.io/](https://ks89.github.io/angular-modal-gallery-2018-v7.github.io/)

**Comment by Ks89** [comment]
Branch 700 merged into develop 🥇

**Comment by Ks89** [comment]
I need at least another beta to fix some stuff on mobile devices, before to go to RCs.

**Comment by Ks89** [comment]
Beta 3 will be released in some days. I also added a new api to add responsive breakpoints to carousel's previews. This is a way to fix responsiveness on previous betas, but also a way to configure heights on previews.

**Comment by Ks89** [comment]
Finally I fixed everything except for a stupid issue on IE11, that I'll fix before the final release.

Next releases will be RCs. If you want to use this library in your project, now you can, because apis are quite stable. Please give me all feedbacks.

**Comment by Ks89** [comment]
7.0.0 RC.1 released :)

The library is stable, or at least I hope.
I have to improve unit testing before the final release, but the library itself it sill be the same as RC1

**Comment by Ks89** [comment]
I'm working on RC2 and hopefully the last RC before to release the final version.
I'm writing unit tests for the two new components. So in RC2 I'll improve input validation and so on, to prevent possible issues.

Please be patient. The final version will be released this month.

**Comment by Ks89** [comment]
RC2 is out.
I'm sorry for the delay but I was really unexpectedly busy this month.
I'll release the final version in 1 or 2 weeks.

**Comment by Ks89** [comment]
7.0.0 will be released today evening :)

**Comment by Ks89** [comment]
7.0.0 final is finally available on npm
