### ISSUE TITLE
9.0.0 Features/Roadmap - MAJOR RELEASE

### ISSUE THREAD

**Issue by Ks89** [Ks89/angular-modal-gallery#227]
I want to start to think about angular-modal-gallery 9.0.0. In particular I want to create a list with some possibile features.

**9.0.0 [Project board](https://github.com/Ks89/angular-modal-gallery/projects/2) to see progress**

Changes in **9.0.0**

- [x] #235 **(BREAKING CHANGE)**
- [x] remove keyCode in keyboard-navigation.directive.ts (drop IE11) #200 **(BREAKING CHANGE)**
- [x] #228 **(BREAKING CHANGE)**
- [x] #229 **(BREAKING CHANGE)**
- [x] #230 **(BREAKING CHANGE)**
- [x] upgrade main example with the new APIs
- [x] upgrade other examples with the new APIs (/examples folder)
- [x] upgrade stackblitz example
- [x] update tests for carousel component
- [x] update tests for carousel-previews component
- [x] upgrade carousel APIs on doc website
- [x] upgrade carousel examples on doc website
- [x] #242
- [x] #241 **(BREAKING CHANGE)**
- [x] #240 **(BREAKING CHANGE)**
- [x] #239 **(BREAKING CHANGE)**
- [x] #231
- [x] #232 **(BREAKING CHANGE)**
- [x] #233 **(BREAKING CHANGE)**
- [x] carousel should work also with 0 images or at least show a loading spinner #209
- [x] #236
- [x] #238 **(BREAKING CHANGE)**

Optional with low priority
- [ ] #208 
- [ ]  #223 

<br><br>
I'll release alphas, betas and so on as always. Feel free to report feedbacks and ideas.

**Comment by Ks89** [comment]
Version 8.0.0 was very huge so with this new release it's time to improve what I made in 8.0.0 and remove deprecated stuff, like IE11, because Angular 13 won't support IE.

**Comment by Ks89** [comment]
To be transparent I created a Project board for both version 9.0.0 and 10.0.0

As you can see I scheduled most of the new features to 10.0.0, because I want to release 9.0.0 as an improvement release with many breaking changes (required to remove IE11 legacy code)

**Comment by Ks89** [comment]
I already implemented some features and I pushed everything into branch called `900`

**Comment by Ks89** [comment]
Upgraded to angular 13.0.0:
- library
- main example
- other examples
- doc website


There is only one missing thing in the "migration" page of the official doc website to release 9.0.0 final.
I hope to release 9.0.0 this weekend

**Comment by Ks89** [comment]
released on npm
doc website available here: https://ks89.github.io/angular-modal-gallery-2021-v9.github.io/
