### ISSUE TITLE
5.0.0 Features/Roadmap (READY TO RELEASE TODAY) - HUGE MAJOR RELEASE

### ISSUE THREAD

**Issue by Ks89** [Ks89/angular-modal-gallery#80]
I want to start to think about angular-modal-gallery 5.0.0. In particular I want to create a list with some possibile features.

I'll leave this list here for one month or more, before to start the implementation. I'll also update readme to encourage users to read this issue. I really need some feedbacks.

- [x] Rewrite SCSS/CSS layout with **FLEXBOX** fixing some well known bugs #98 #37 (BREAKING CHANGE)
- [x] Performance improvements with trackById and OnPush (BREAKING CHANGE) (Commit 3cb56435f0426c715ca442cd1e7a6a5cc222c3b9 and #103)
- [x] Improve accessibility with ARIA #99 (BREAKING CHANGE)
- [x] Remove Angular 2 support (for instance replace Renderer with Renderer2) #70 (BREAKING CHANGE)
- [x] Update to Angular 5 #83
- [x] Partial support to Server-Side-Rendering (SSR) with Angular Universal #81 (BREAKING CHANGE)
- [x] Try to add support for IE11 using navigator.mssaveblob #39
- [x] General refactoring reorganizing the structure of this project and splitting some components #42 (BREAKING CHANGE)
- [x] new class Image API (with modal and plain inner objects) (BREAKNIG CHANGE)
- [x] Try to add this big and important feature: "Improve modal layout with small previews and eventually also animations" #48 (BREAKING CHANGE)
- [x] Thumbnail size/more options #91 (BREAKNIG CHANGE)
- [x] Completely rewrite "imagepointer feature" #49 (BREAKING CHANGE)
- [x] Try to support this feature: "Square thumbnails" #76 (BREAKING CHANGE)
- [x] Fix bug on Microsoft Edge Desktop #108 
- [x] Support configurable buttons with custom actions #79 and #92 (BREAKING CHANGE)
- [x] Support "https://github.com/mgechev/angular-seed" #56 (it's also working with angular-modal-gallery >= 4.0.0)
- [x] Infinite sliding will be disabled by default #84 (BREAKING CHANGE)
- [x] Click Outside will be enabled by default #85 (BREAKING CHANGE)
- [x] Which is the best place for image description? Think about it. [I decided to use html's tag figurecaption ] [DONE - This feature will be released with #98]
- [x] remove Observable<Image[]> as input. I decided to switch to Image[] to simplify the sourcecode #105  (BREAKING CHANGE)
- [x] Update systemjs example to 5.0.0
- [x] Update webpack example to 5.0.0
- [x] Update angular-cli example to 5.0.0
- [x] Add new universal example to use SSR 
- [x] Add new angular-cli-material example with Angular Material (still some issues to build it with circleci, jenkins and appveyor. However, travis and my local pc are working very well...so why???)
- [x] Remove all deprecated APIs (both showDownloadButton and showExtUrlButton)
- [x] Update unit testing to 5.0.0
- [x] Update public documentation website to 5.0.0
- [x] Add a MINIMAL migration guide from 4.x.x to 5.0.0
- [x] Publish public documentation website on a private VPS
- [x] Update library documentation with typedocs to 5.0.0
- [x] choose which are the right entry points in package.json as described by angular package format 5 specifications 
- [x] add credits and licenses to all images, icons and so on
- [x] add onpush strategy also to modal-gallery.component
- [x] prevent browser scrolling when modal gallery is opened
- [x] add sonarcloud.io
- [x] switch from plnkr.co to stackblitz.com
- [x] release the umd bundle on a CDN like unpkg.com (update: available [HERE](https://unpkg.com/angular-modal-gallery@5.0.0-beta.1/bundles/angular-modal-gallery.umd.min.js) )
- [x] test everything on IE11, Edge, iOS, Android...and what about iPhone X?

This issue will be updated every time I'll implement something on a [dedicated branch 'develop'](https://github.com/Ks89/angular-modal-gallery/tree/develop) 

**I will be really happy if you want to create pull requests or you want to talk with me about features, before the official release. So I'll be able to change my roadmap accordingly.**

**Comment by Ks89** [comment]
Branch for v4 https://github.com/Ks89/angular-modal-gallery/tree/v4

**Comment by Ks89** [comment]
New experimental branch created from v4 here: https://github.com/Ks89/angular-modal-gallery/tree/v4-experimenting-packagr

**Comment by Ks89** [comment]
Branch https://github.com/Ks89/angular-modal-gallery/tree/v4-experimenting-packagr merged into  https://github.com/Ks89/angular-modal-gallery/tree/v4

**Comment by Ks89** [comment]
Renamed as version 5.0.0 because I have to release a new major version to add Angular 5 support to version 3.x. 
To match semver specifications, I have to release it as 4.0.0, due to a breaking change for systemjs users.

**Comment by Ks89** [comment]
Angular 5 support re-scheduled for angular-modal-gallery 4.0.0

**Comment by Ks89** [comment]
Configurable buttons implemented in a private branch locally. Please, be patient.

**Comment by Ks89** [comment]
Server-Side-Rendering (SSR) partially implemented. I still have a non blocking issue about Mousetrap.
Also I added an official example with angular-universal.

**Comment by Ks89** [comment]
angular-seed is now officially supported (it was working also with >= 4.0.0)

**Comment by Ks89** [comment]
I'm not dead :)
At the beginning of December I will release the first alpha version of angular-modal-gallery 5.0.0.

Also, I'll push the source code on github. At the moment, I'm working privately, because It is really experimental and I need some privacy :)

**Comment by Ks89** [comment]
remove Observable<Image[]> as input. I decided to switch to Image[] to simplify the sourcecode (BREAKING CHANGE) implemented

**Comment by Enngage** [comment]
Hi, you know when you are gonna release it?

**Comment by Ks89** [comment]
@Enngage 
The first alpha will be released at the beginning of December.
I'll also create a plunker to test all available features.

PS: do you want to be a beta tester?
Because, apis will be different and I really need some suggestions. In this way I can change apis during alphas.
I want to define apis before the end of December.

PS: at the beginning of december, all "modal features" will be available as alpha-1. However all "plain features" (or "inline features) won't be available, because I din't implement anything, at the moment. Everything "checked" right now in the TODO list will be released as alpha-1. All others, will be available during december.

**Comment by Ks89** [comment]
Update to Angular package format v 5.0 specifications #106  

https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs

Scheduled for 5.0.0 alpha-1

**Comment by Enngage** [comment]
I'm not sure what you mean by beta testing, but I will update your library as soon as its out and will let you know any issues I encounter. My project is already on Angular 5 so there should be no problems there.

**Comment by Ks89** [comment]
Ok perfect. Thank u. 

PS in all alphas I'll add all missing features (not. Production ready) and finally in betas I'll write tests and fix bugs.

**Comment by Ks89** [comment]
[5.0.0 alpha 1](https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-alpha.1) released
and also
[5.0.0 alpha 2](https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-alpha.2) released

There is also a plunkr example here: https://embed.plnkr.co/kzrd05/

@Enngage what do you think? Obviously, the official doc is still not available, however I created many examples here https://github.com/Ks89/angular-modal-gallery/tree/v4/examples

**Comment by Enngage** [comment]
Awesome, I like the examples a lot thus far, especially the buttons which I will put into use. 

I noticed an issue when you select first/last image which causes side images on that particular side to not show at all, but I suppose this is what you mean in your PS2 :-)

Additionally, from my humble testing I noticed that the margin of the right arrow does not match the one on the left. Maybe this is caused by the overflow on the page? Not sure, haven't had the time to look at it in more detail yet. 

![right_margin](https://user-images.githubusercontent.com/7137351/33540276-a56b4b8a-d8ca-11e7-81d2-d803a90ff9f3.png)

I will probably update during weekend and will post any issues I encounter. 

Maybe I have a question actually, in previous build I used custom images template (https://ks89.github.io/angular-modal-gallery.github.io/demo/array-pointer) which is extremely useful and probably necessary for most situations. How does this work in the new version?

Thanks for the continuous support :-)

**Comment by Ks89** [comment]
> I noticed an issue when you select first/last image which causes side images on that particular side to not show at all, but I suppose this is what you mean in your PS2 :-)

Yes this is exactly the PS2, I'll fix it ASAP.

<br>

> Additionally, from my humble testing I noticed that the margin of the right arrow does not match the one on the left. Maybe this is caused by the overflow on the page? Not sure, haven't had the time to look at it in more detail yet.

Yes this is really frustrating. I'm using the viewport so there are some problems with scrollbars. I'll try to remove scrollbars when the modal gallery is open in next alphas. (Also, I'll try to remove scrolling, but I'm not sure how to implement it)
<br>

> in previous build I used custom images template (https://ks89.github.io/angular-modal-gallery.github.io/demo/array-pointer) which is extremely useful and probably necessary for most situations. How does this work in the new version?

This is one of the main features that I want to rewrite. The idea is to re-design this feature in a better way to give more power to users.

**Comment by Ks89** [comment]
> Additionally, from my humble testing I noticed that the margin of the right arrow does not match the one on the left. Maybe this is caused by the overflow on the page? Not sure, haven't had the time to look at it in more detail yet.

Ok I found a quick and simple solution to this problem hiding scrollbars (2 lines of code :)).
I'll push alpha 3 this weekend.

**Comment by matiishyn** [comment]
hi
how can I install this new 5 beta version?

**Comment by Enngage** [comment]
You can use either

`npm install angular-modal-gallery@next`

or edit existing package.json like:

`"angular-modal-gallery": "next"`

**Comment by Ks89** [comment]
If any of you are using Microsoft Edge, please could you try the alpha 2 on plnkr.co (https://embed.plnkr.co/kzrd05/) on that browser?

I don't know why, but I found a bug on Edge Desktop #108

**Comment by Ks89** [comment]
Alpha 3 released with some bugfixes and improvements [HERE](https://github.com/Ks89/angular-modal-gallery/releases)

`npm install angular-modal-gallery@next`

or

`npm install angular-modal-gallery@5.0.0-alpha.3`

**Comment by Ks89** [comment]
Alpha 4 released with plain gallery [HERE](https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-alpha.4)

`npm install angular-modal-gallery@next`

or

`npm install angular-modal-gallery@5.0.0-alpha.4`

[Click here for the official plnkr.co demo](https://embed.plnkr.co/kzrd05/)

**Feel tree to comment this new version and APIs. In alpha stage I can change eveything, so If you have an idea, please share it with me here.**

@Enngage I modified Image API as suggested by you in this issue #91 Obviously it is a first implementation. In future releases I'll add the feature to add custom configuration, different for every image. With 5.0.0 final I want to release the simpler version.

**Comment by odahcam** [comment]
Do you have any plans on supporting touch like https://codepen.io/odahcam/pen/WdZbev ?

**Comment by Ks89** [comment]
@odahcam Hi! thank you for the answer.

Touch is supported on mobile devices. You can swipe between images. It's not intended to be used also on desktops with a sort of drag effect, but it is a pure 'swipe'. You can try using chrome dev tools in smartphone's view.

Also, I'll add animation with `@angular/animations` to create swipe effects... in future 5.x.x releases. At the moment, I added simple and pure css animations.

**Comment by Ks89** [comment]
Hi guys!
Alpha 5 released [HERE](https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-alpha.5)

`npm install angular-modal-gallery@next`

or

`npm install angular-modal-gallery@5.0.0-alpha.5`

**[Click here for the official plnkr.co demo](https://embed.plnkr.co/kzrd05/)**

**Feel tree to comment this new version and APIs. In alpha stage I can change eveything, so If you have an idea, please share it with me here.**

Be careful because I modified a little bit an API. It's a very small change.

PS: next version should be the first BETA. Now I'm writing unit tests fixing some bugs.

APIs should be stable right now. I'll add breaking changes only if really needed.

**Comment by Enngage** [comment]
Hey,

Thank you, I'm migrating to new version :-)

One thing I noticed is that if the images have different dimensions (i.e. one is 'taller' than another), the right / left arrows at the screen edges are placed incorrectly. For example, it may happen that if you don't move your mouse and keep clicking on the arrow, at some point the arrow will move up or down and you will close the modal (if enabled) or the image will not be switched because you didn't click on the arrow.

**Comment by Enngage** [comment]
Another thing - 'ButtonType.EXTURL' button will open the image in the same window. Can you possibly use 'target="_blank"' instead? Either automatically as its very common or at least as a property that can be set?

**Comment by Enngage** [comment]
And another one (sorry for spamming here) - I have a custom delete button and it works fine, but the thing is that I'm removing the from the collection passed as `modalImages` in the `onButtonBeforeHook` event which does not actually remove the currently opened modal image. I suppose there should be some way of force refreshing the library for such scenario.

**Comment by Ks89** [comment]
> One thing I noticed is that if the images have different dimensions (i.e. one is 'taller' than another), the right / left arrows at the screen edges are placed incorrectly. For example, it may happen that if you don't move your mouse and keep clicking on the arrow, at some point the arrow will move up or down and you will close the modal (if enabled) or the image will not be switched because you didn't click on the arrow.

Damn. Please could you same images to reproduce this behaviour?

> Another thing - 'ButtonType.EXTURL' button will open the image in the same window. Can you possibly use 'target="_blank"' instead? Either automatically as its very common or at least as a property that can be set?

Good idea. It's very easy to implement, so I can add it to the next version.

> And another one (sorry for spamming here) - I have a custom delete button and it works fine, but the thing is that I'm removing the from the collection passed as modalImages in the onButtonBeforeHook event which does not actually remove the currently opened modal image. I suppose there should be some way of force refreshing the library for such scenario.

This is something that I should really explain very well before the final release because It's not easy to understand. Probably, this is cause because you are removing data from the array without re-initializing it. Check example B18 here https://plnkr.co/edit/kzrd05?p=preview

**Comment by Ks89** [comment]
@Enngage  Add  optional 'target="_blank"' to navigate button #116 implemented in v4 branch and ready to release it with the next version 👍

**Comment by Ks89** [comment]
@Enngage I tried with images of different sizes and I confirm that behaviour.
I thought that the problem was the horizontal alignment, but it's the opposite, because they move vertically. I have to investigate...

**Comment by Ks89** [comment]
@Enngage 

This weekend I'll release the last alpha with fixes for:
-  this issue:

> One thing I noticed is that if the images have different dimensions (i.e. one is 'taller' than another), the right / left arrows at the screen edges are placed incorrectly. For example, it may happen that if you don't move your mouse and keep clicking on the arrow, at some point the arrow will move up or down and you will close the modal (if enabled) or the image will not be switched because you didn't click on the arrow.

- this: 

> Another thing - 'ButtonType.EXTURL' button will open the image in the same window. Can you possibly use 'target="_blank"' instead? Either automatically as its very common or at least as a property that can be set?

And lot of other fixes and better unit testing.

**Comment by Ks89** [comment]
Ok, I decided to release Beta 1 today 👍 

To install:

`npm install angular-modal-gallery@next`

or

`npm install angular-modal-gallery@5.0.0-alpha.5`


Official live demo: https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-beta.1

Changelog here: https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-beta.1

Roadmap: Now I have to work on some betas and RCs to fix bugs, add missing tests and write the new documentation website. However, at the end of February I'll release the final version! Hope you like it 👍

**Comment by vugar005** [comment]
@Ks89  Please update to font-awesome v5.

**Comment by Ks89** [comment]
Hi @vugar005 font-awesome is not mandatory in Angular modal gallery 5. You can use custom css classes for upper buttons if you want. 
PS: fortawesome is working to add angular support. At the moment is not officially available.

**Comment by vugar005** [comment]
@Ks89  the problem is when using font awesome v5 with the plugin. The icons not showing. the 
exclamation is shown instead.

**Comment by Ks89** [comment]
Mmm,  no wait, I didn't understand what you are saying. Could you explain?

**Comment by Ks89** [comment]
Beta 2 in finally available:

To install:

npm install angular-modal-gallery@beta

or

npm install angular-modal-gallery@5.0.0-beta.2

I replaced plnkr with stackblitz, so:
Official live demo: https://stackblitz.com/edit/angular-modal-gallery-v5

Changelog here: https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-beta.2

**Comment by Ks89** [comment]
RC 1 in finally available:

To install:

npm install angular-modal-gallery@beta

or

npm install angular-modal-gallery@5.0.0-rc.1

Official live demo: https://stackblitz.com/edit/angular-modal-gallery-v5

Changelog here: https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-rc.1

PS: I'm working on the official documentation for 5.0.0. This weekend (probably tomorrow) I'll release the first draft on github pages (different URL of the existing version, because I don't want to overwrite the documentation of 4.x.x).

The final version is still scheduled for the end of February. No unexpected delay, at the moment :).

**Comment by Ks89** [comment]
Website for versions >= 5.x.x created with an initial documentation (still not complete and with lot of missing things, so please be careful. I need at least an entire week to add all important stuff, so please be patient).

At the moment, this website il build with angular-modal-gallery 4 :) and all demos are removed. I updated "getting started", "features" and "migration guide" (all these pages are still draft).

URL: https://ks89.github.io/angular-modal-gallery-2018.github.io/

<img width="1916" alt="schermata 2018-02-18 alle 00 52 50" src="https://user-images.githubusercontent.com/6057207/36346788-6cb08d5c-1446-11e8-84df-1d8d141663dd.png">

**Comment by Ks89** [comment]
RC 2 with a very small changelog (I temporary removed refresh button because it wasn't working as expected)

To install:

npm install angular-modal-gallery@beta

or

npm install angular-modal-gallery@5.0.0-rc.2

Official live demo: https://stackblitz.com/edit/angular-modal-gallery-v5

Changelog here: https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-rc.2

The final version is still scheduled for the end of February. No unexpected delay, at the moment :).

This weekend I'll post the first complete draft of the documentation website.

PS: I updated the official github's readme with better descriptions and other stuff [HERE](https://github.com/Ks89/angular-modal-gallery/tree/develop)

**Comment by Ks89** [comment]
I'm sorry guys for this unscheduled release, but I found a bug and I had to fix it very quickly.

RC 3 with a very small changelog (fix full description)

To install:

npm install angular-modal-gallery@beta

or

npm install angular-modal-gallery@5.0.0-rc.3

Official live demo: https://stackblitz.com/edit/angular-modal-gallery-v5

Changelog here: https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.0.0-rc.3

**Comment by Ks89** [comment]
First full draft of the doc website with demos and other fixes.

https://ks89.github.io/angular-modal-gallery-2018.github.io/ 

Next week I'll release the final version as expected.

**Comment by ckelkar** [comment]
![image](https://user-images.githubusercontent.com/15060815/36743826-d63a7df2-1bb0-11e8-8900-b456e4ed554c.png)

Hello @Ks89 ,
Is there any way I can add html and css for styling description mentioned in the image? Actually I am getting some data regarding each image from API and I want to show it using bullet points. 

Also I am using <ks-modal-gallery>. Is this previous version? Do I need to upgrade myself to stable one?

Thanks.

**Comment by Ks89** [comment]
Hi @ckelkar.
At the moment you can change css as you want (because it's simply css :)), however html is not supported, but it could be a good feature for future releases (5.x.x because I don't expect braking changes to do that). I opened an issue with this feature.

The version that you are using is correct and it's a beta/rc. Today I'll release the stable version.

**Comment by Ks89** [comment]
5.0.x is out after months of work

![image](https://user-images.githubusercontent.com/6057207/36759724-a6a0151c-1c18-11e8-8f55-d44f532e8da1.png)

**Comment by ckelkar** [comment]
Hi @Ks89 ,
Thank you. Also I am struggling with adding  { length: 10, wrap: true } to Custom gallery layout. I have seen class structure. Only LineLayout, GridLayout has that feature. How should I add it to the AdvancedLAyout?

**Comment by Ks89** [comment]
if you want a custom layout you have to build everything by yourself. Check my official example (on stackblitz or also inside my repo in examples folder) or also in the doc.

So limit is like a ngFor to only some of the input images.
wrap is simply the flex-wrap property https://www.w3schools.com/cssref/css3_pr_flex-wrap.asp

So you have to build a flexbox container with inside a ngFor to iterate over your images.

If you see my examples I made a demo adding also descriptions over plain images.

**Comment by Ks89** [comment]
Hi @ckelkar I implemented HTML description support as you asked previously in 5.0.0-beta.1
https://github.com/Ks89/angular-modal-gallery/releases/tag/v5.1.0-beta.1

If you are interested, please add a comment or activate notification to this issue https://github.com/Ks89/angular-modal-gallery/issues/123, so I can ignore this one (#80) forever, because there are many people here and I don't want to spam their.

**Comment by andrei8788** [comment]
Hello. At me at loading component slowly are loaded pictures!
![src](https://user-images.githubusercontent.com/32166538/42227877-38457716-7eeb-11e8-88d5-61ffc8291ac7.jpg)
Their location is set by:
plainGalleryGrid: PlainGalleryConfig = {
    strategy: PlainGalleryStrategy.GRID,
    layout: new GridLayout({ width: '319px', height: '210px' }, { length: 4, wrap: true })
  };
in the template:
    <ks-modal-gallery [id]="0" [modalImages]="images"
                      [plainGalleryConfig]="plainGalleryGrid"
    ></ks-modal-gallery>
Can this be fixed with the help of this library?

**Comment by Ks89** [comment]
Hi @andrei8788 the browser requests images automatically to display they, so it will be loaded asynchronously on demand.

Also i suggest to decrease the size of images if possible, using smaller thumbs and bigger modal images. 

However, are you searching a way to preload images?

**Comment by andrei8788** [comment]
I would use any method to avoid this. Can I add some animation? I'll try to reduce the size of the pictures, but I would like the pictures to be in good quality. I have been trying to solve the problem more than one day and nothing happens. For any of your advice I will be very grateful!

**Comment by Ks89** [comment]
Ok, first use thumbs with a small images (not highly simply compressed, to prevent quality loss) using lower resolutions. From your screen it seems that there are many images on the same screen, so it could be useless to have images with 4k resolution and so on.

For the modal image use another one, with higher resolution.

I didn't think about animations in plain gallery, but it could be a good idea for next releases.

PS: which network are you using? Did you measure the speed in kb/s? Because the problem it's the library itself, but either slow network or giant images.

I cannot promise anything but I'm thinking to rewrite plain gallery with more features. However, this summer I'm really busy and probably I won't be able to release as 7.0.0, but as 8.0.0.

**Comment by andrei8788** [comment]
Thank you for your help! It will be nice to see the updated version, but the current one I like too!

**Comment by andrei8788** [comment]
Сеть:
![s](https://user-images.githubusercontent.com/32166538/42239537-e5163978-7f0c-11e8-907a-25e6f425d0a8.JPG)

**Comment by andrei8788** [comment]
Once again many thanks! The problem is solved.
